server:
  port: 8082

spring:
  application:
    name: order-processing-app
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    driverClassName: org.postgresql.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:19091
    consumer:
      group-id: my-app
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  liquibase:
    change-log: changelog-master.xml
    enabled: true
app:
  async:
    thread-pool:
      core-size: ${ASYNC_CORE_POOL_SIZE:4}
      max-size: ${ASYNC_MAX_POOL_SIZE:4}
      queue-capacity: ${ASYNC_QUEUE_CAPACITY:100}
      thread-name-prefix: ${ASYNC_THREAD_PREFIX:AsyncTask-}
      wait-for-tasks: ${ASYNC_WAIT_FOR_TASKS:true}
resilience4j:
  circuitbreaker:
    instances:
      databaseService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      emailService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  # Konfiguracja retry
  retry:
    instances:
      databaseService:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.dao.DataAccessException
          - java.sql.SQLException
      emailService:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - org.springframework.kafka.KafkaException
          - java.io.IOException
  timelimiter:
    instances:
      databaseService:
        timeoutDuration: 5s
      emailService:
        timeoutDuration: 3s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,retries
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true
    retries:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka